/** @type {import('tailwindcss').Config} */
module.exports = {
  presets: [require('nativewind/preset')],
  content: ['./app/**/*.{ts,tsx}', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        app: '#121212',
        'app-alt': '#0d0d11',
        card: '#1a1423',
        'card-muted': '#17111f',
        panel: '#241733',
        sheet: '#ffffff',
        primary: '#ffffff',
        secondary: '#d8d7e1',
        muted: '#9f9fb3',
        subdued: '#7b7589',
        dark: '#121212',
        error: '#ffb4b4',
        'border-card': '#2b2340',
        'border-accent': '#8b5cf6',
        'border-muted': '#4c3b67',
        brand: '#8b5cf6',
        'brand-soft': '#ba9ef8',
        'brand-strong': '#a855f7',
        'brand-deep': '#5f4d83',
        'sheet-handle': '#d1d5db',
        'ghost-bg': '#efe7f6',
        'thumb-bg': '#2b2340',
        ink: '#101418',
        surface: '#f5f0e8',
        sand: '#e6dccd',
        ember: '#d65a31',
        moss: '#345c4d',
        line: '#d7c9b5',
      },
      borderRadius: {
        xl2: '18px',
        xl3: '24px',
        xl4: '28px',
      },
      spacing: {
        4.5: '18px',
      },
    },
  },
  plugins: [],
};
